[T] (quests) want_not
ShaBaiTianCN/FTB-Inferno pull request #12
Opened 2022-12-01 02:12 UTC by Annijang

2022-12-01 03:14 UTC, xinyihl approved these changes

2022-12-01 05:49 UTC, Ricky-fight requested changes

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在该领域的最深处，有一只&6巨型类似鲨鱼&r的恶魔霸主。"
```suggestion
				"在该领域的最深处，有一只类似&6巨型骷髅鲨鱼&r的恶魔霸主。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&b虚空蠕虫&r是所有世界的守护者，击败它我将获得它的力量，当&与&6我的意志结合&r起来时我将获得&6突破虚空的力量&r。"
```suggestion
				"&b虚空蠕虫&r是所有世界的守护者。击败它，&6将它的力量与我的意志结合&r，我将获得&6突破虚空的力量&r。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"随着虚空蠕虫的倒下，我获得了&6研究顶级科技的能力&r，并最终从这可恶的监狱中解脱！"
```suggestion
				"随着虚空蠕虫的倒下，我获得了&6研究顶级科技的能力&r，并最终从这该死的监狱中解脱！"
```
怀疑你在卖萌（doge

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在将我的大学升到5级时，我获得了&6卓越研究&r的成就，并最终可通过一扇标准的下界传送门的形状去前往属于我的世界。"
```suggestion
				"将我的大学升到5级后，我获得了&6卓越研究&r的成就，并最终可通过一扇标准的下界传送门前往属于我的世界。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"低等级的工人&c只能使用低级的工具&r，这包括盔甲、武器和工具等。因此，越高等级的工人越应该使用越好的工具。"
```suggestion
				"低等级的工人&c只能使用低级的工具&r，这包括盔甲、武器和其它工具等。另外，高等级的工人需要使用高等级的工具。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"一个2级的工人显然可以使用2级的工具，但是也能使用&6已附魔的1级工具&r。工具拥有的每一级附魔都会使该工具的使用等级+1,一把拥有5级附魔的工具可以被任何工人使用，附魔数量无限制。"
```suggestion
				"一个2级的工人显然可以使用2级的工具，但是也能使用&6已附魔的1级工具&r。工具拥有的每一级附魔都会使该工具的使用等级+1,一把拥有5级附魔的工具可以被任何工人使用，附魔数量没有要求。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +			subtitle: "是什么让你与众不同！"
```suggestion
			subtitle: "是什么让你的刁民与众不同！"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"每位工人都有11种&b技能&r，他们每位的技能都是独一无二的。"
```suggestion
				"每位工人都有11种&b技能&r，他们每种技能的等级都不一样。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"每种疾病都需要某些物品来治疗，一些更威胁的疾病可能需要进行某些魔法类的研究才能彻底治疗。"
```suggestion
				"每种疾病都需要某些物品来治疗，一些更具威胁的疾病可能需要进行某些魔法类的研究才能彻底治疗。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&c不要尝试频繁地取消建造过程&r，因为这只会让工人频繁地从头开始，从而重新检查每个方块的位置，这对于大型建筑来说，将会消耗更长更久的时间。"
```suggestion
				"&c不要尝试频繁地取消建造过程&r，因为这只会让工人频繁地从头开始，从而重新检查每个方块的位置，这对于大型建筑来说，将会消耗更久的时间。"
```
不是一个意思么

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&o然而，&r有时他们也会因为&l一些原因而卡住&r，这种情况比较明显，比如说工人被卡在书上等，只需要将他们重新部署，他们就会继续工作。"
```suggestion
				"&o然而，&r有时他们也会因为&l一些原因而卡住&r，这种情况比较明显，比如说工人被卡在树上等，只需要将他们重新部署，他们就会继续工作。"
```
是重新部署么

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +			subtitle: "建筑工人的批量请求"
```suggestion
			subtitle: "建筑工人分批请求"
```
batch这里作动词：分批处理，与下文对应

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&b弓箭手&r是远程型卫兵。他们穿戴盔甲，手持远程武器，并且他们无需弓箭，如果在大学里解锁了相关研究，那么弓箭手也能造成更高的伤害。"
```suggestion
				"&b弓箭手&r是远程型卫兵。他们穿戴盔甲，手持远程武器，并且他们不消耗弓箭，如果在大学里解锁了相关研究，那么弓箭手也能造成更高的伤害。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"工人&b可以学习合成功能&r，并学会如何制作物品。"
```suggestion
				"工人&b可以学习合成功能&r，并且会根据请求来合成物品。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&6不同的职业可制作不同的物品。&r你可以在JEI中查看到每种职业能够合成出来的物品。"
```suggestion
				"&6不同的职业可制作不同的物品。&r你可以在 JEI 中查看到每种职业能够合成出来的物品。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&6必要为工人设置合成配方&r，这是在工作区域的标签中完成的。"
```suggestion
				"合成配方&6需要手动为工人设置&r，工作方块的界面有一个相关的标签页。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"设置配方时，你可以从JEI中拖动物品，配方会&c无视tag标签&r。"
```suggestion
				"设置配方时，你可以从 JEI 中拖动物品，配方会&c无视 tag 标签&r，只会使用学习配方时指定的原材料。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在市政厅的&b许可&r选项中，你可以设置其他玩家与你殖民地的关系。"
```suggestion
				"在市政厅的&b权限&r选项中，你可以设置其他玩家与你殖民地的关系。"
```

2022-12-01 05:49 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"工人能打开门、活板门等等，甚至可以在没有红石信号的前提下强行使用铁门！他们也会使用梯子、藤蔓，并避免火和熔岩。"
```suggestion
				"工人能打开门、活板门等等，甚至可以在没有红石信号的前提下强行使用铁门！他们也会使用梯子、藤蔓，并避开火和岩浆等等。"
```

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在这些任务章节中的信息无时无刻都在提醒我，我现在就必须要去建造一座&6渔夫小屋&r和&6采石场&r，因为我非常需要他们来为我提供接下来所需要的资源。"
> 这个和原文意思有点差别，不过好像没关系（？

要读起来流畅一些就需要加一些其他内容。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&o完成本任务即可解锁&3本主章节&r中的&5在服务内&r和&5给他一条鱼&r大章节任务。"
> 这个不同章节里任务书的翻译格式有待统一

汉化时已在石墨更新。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"建筑工无法建造那些比建筑工小屋的等级更高的建筑，所以如果想建造一座2级的房屋，就需要将建筑工小屋升到2级。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&o随着殖民地的发展，我们将会需要更多的卫兵塔来守卫这片区域，以便为新的居民腾出更多的房子。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"现在他们始终都在抱怨他们“不敢工作”！这种工作怎么能停止呢！？"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +					command: "/tellraw @p [\"\",\"解锁该章节\",{\"text\":\"在服务内 \",\"color\":\"dark_purple\"},\"under \",{\"text\":\"欲望\",\"color\":\"dark_aqua\"},\"!\"]"
> 

汉化时已同步更新汉化名。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +					command: "/tellraw @p [\"\",\"解锁该章节\",{\"text\":\"给他一条鱼 \",\"color\":\"dark_purple\"},\"under \",{\"text\":\"欲望\",\"color\":\"dark_aqua\"},\"!\"]"
> 章节名、翻译句式待统一

汉化时已同步更新汉化名。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&o越高等级的工人越需要更好的食物，而不是吃劣质食物。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"虽然&b市政厅&r作为最明显的中心点，但是我发现我最好也将&6仓库&r也建在我的中心点附近。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"现在建筑已经逐渐开始成型，但是我发现在殖民地中物流仍然是一个噩梦般的存在。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"这些工具十分地粗糙，虽然挖掘速度慢但却&6非常耐用&r，可以提供惊人的65,000点使用次数，可用于去开采原木。"
> durability游戏里一般叫耐久吧，还有开采原木什么鬼

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"建筑物周围需拥有合适的结构框架，无需担心&6建筑工&r如何到达那里。任务奖励的胶囊能放置指定结构，而只需要去确认它们被放置的位置即可。这可能仍然需要一段时间，因为建筑工建造建筑需要的时间会&6根据该建筑的大小而变化&r。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在每个建筑的GUI中，都有一个&6建筑选项&r的按钮。在选项里，可以查看到所有的建筑都是由框架与方块组成的。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在选项的底部，你可以让建筑工人去&b建造建筑或者升级建筑&r。"
> 修复

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"温馨提示：二级的建筑需要二级的建筑工人小屋！"
> 与上文统一

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"为了解锁三级大学，需要使用&bDame Fortuna Gateway珍珠l&r去召唤并击败&6福尔图娜女爵&r。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在击败福尔图女爵后，我可以制作&bArk of Infernal Insight&r，可将大学再升一级。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"随着我的殖民地的发展，我能继续&6升级我的大学&r。能让我继续去做我的&4炼狱研究&r，解锁更多建筑都起到了极其重要的作用。"
> 

谢谢提醒，已更改

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"注意：恶魔霸主注意到了我击杀了它们的人，从现在开始，将会有许多&c源源不断地怪物产生&r。"
> 恶

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +					command: "/tellraw @p [\"\",\"在\",{\"text\":\"大学中\",\"color\":\"red\"},\"学习了炼狱研究后，已经准备好了去迎接更多怪物的洗礼了。\"]"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +					command: "/tellraw @p [\"\",\"详细内容请请查看\",{\"text\":\"保护平民\",\"color\":\"dark_purple\"},\"under \",{\"text\":\"章节中的任务。\",\"color\":\"dark_aqua\"}]"
> 

可后续再改，我在汉化时已将译名统一

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在该领域的最深处，有一只&6巨型类似鲨鱼&r的恶魔霸主。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&b虚空蠕虫&r是所有世界的守护者，击败它我将获得它的力量，当&与&6我的意志结合&r起来时我将获得&6突破虚空的力量&r。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"随着虚空蠕虫的倒下，我获得了&6研究顶级科技的能力&r，并最终从这可恶的监狱中解脱！"
> 怀疑你在卖萌（doge

喵φ(>ω<*)

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"在将我的大学升到5级时，我获得了&6卓越研究&r的成就，并最终可通过一扇标准的下界传送门的形状去前往属于我的世界。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"低等级的工人&c只能使用低级的工具&r，这包括盔甲、武器和工具等。因此，越高等级的工人越应该使用越好的工具。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"一个2级的工人显然可以使用2级的工具，但是也能使用&6已附魔的1级工具&r。工具拥有的每一级附魔都会使该工具的使用等级+1,一把拥有5级附魔的工具可以被任何工人使用，附魔数量无限制。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +			subtitle: "是什么让你与众不同！"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"每位工人都有11种&b技能&r，他们每位的技能都是独一无二的。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"每种疾病都需要某些物品来治疗，一些更威胁的疾病可能需要进行某些魔法类的研究才能彻底治疗。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&c不要尝试频繁地取消建造过程&r，因为这只会让工人频繁地从头开始，从而重新检查每个方块的位置，这对于大型建筑来说，将会消耗更长更久的时间。"
> 不是一个意思么

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&o然而，&r有时他们也会因为&l一些原因而卡住&r，这种情况比较明显，比如说工人被卡在书上等，只需要将他们重新部署，他们就会继续工作。"
> 

殖民地模组我没怎么玩过，我击杀了一名npc后发现他无法复活，除了重新部署我也不知道应该使用其他什么词来替换了。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +			subtitle: "建筑工人的批量请求"
> Reference in n

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"&b弓箭手&r是远程型卫兵。他们穿戴盔甲，手持远程武器，并且他们无需弓箭，如果在大学里解锁了相关研究，那么弓箭手也能造成更高的伤害。"
> 

已更正。

2022-12-01 06:44 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"工人&b可以学习合成功能&r，并学会如何制作物品。"
> 

已更正。

2022-12-01 06:55 UTC, Ricky-fight requested changes

2022-12-01 06:55 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"建筑工比建筑工小屋更高等级的建筑，所以如果想建造一座2级的房屋，就需要将建筑工小屋升到2级。"
这个还是有问题

2022-12-01 06:55 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"这些工具十分地粗糙，虽然挖掘速度慢但却&6非常耐用&r，可以提供惊人的65,000点奶就是，但开采等级只有与木镐一样的等级。"
耐久值

2022-12-01 06:55 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"大学每一升级都需要消耗一定数量的&5特殊物品&r，而二级大学需要&bArk of Infernal Delight&r。"
2级大学

2022-12-01 06:55 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"注意：恶魔霸主注意到了我击杀了它们之中的一个，&c从现在开始将会生成更难缠的的怪物&r。"
更难缠的怪物

2022-12-01 06:56 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"注意：恶魔霸主注意到了我击杀了它们之中的一个，&c从现在开始将会生成更难缠的的怪物&r。"
开review好像开错了，没法直接suggesttion

2022-12-01 06:56 UTC, Ricky-fight commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"注意：恶魔霸主注意到了我击杀了它们之中的一个，&c从现在开始将会生成更难缠的的怪物&r。"
另外你没用add to patch么，手打补丁还是容易出错的

2022-12-01 07:03 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"注意：恶魔霸主注意到了我击杀了它们之中的一个，&c从现在开始将会生成更难缠的的怪物&r。"
不会qwq

2022-12-01 07:05 UTC, Annijang commented on config/ftbquests/quests/chapters/want_not.snbt
> +				"这些工具十分地粗糙，虽然挖掘速度慢但却&6非常耐用&r，可以提供惊人的65,000点奶就是，但开采等级只有与木镐一样的等级。"
淦，按太快没注意qwq

2022-12-03 11:21 UTC, xinyihl approved these changes

2022-12-03 12:59 UTC, AnzhiZhang approved these changes

2022-12-05 03:30 UTC, Ricky-fight approved these changes

2022-12-05 03:31 UTC, merged